x-uffizzi:
  ingress:
    service: app
    port: 80

services:
  app:
    build: .
    environment:
      NODE_ENV: staging
    deploy:
      resources:
        limits:
          memory: 1000M
    restart: always
    ports:
      - "80:80"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
    restart: always
volumes:
  data:
